// Writes src/daemon/web/icons.generated.ts from the Phosphor package.
//
// The daemon used to read these SVGs from node_modules at startup, which meant
// the package had to be installed alongside it. Published, that dragged 37MB of
// icon set into every install to serve two files.
//
// Generating instead keeps what reading from the package was for. The shapes
// are still Phosphor's and still arrive by upgrading the dependency, so nothing
// here is drawn by hand: bump @phosphor-icons/core, run `npm run icons`, and
// read the diff. What changes is that only the two icons travel.
//
// Run: npm run icons

import { createRequire } from 'node:module'
import { readFileSync, writeFileSync } from 'node:fs'

const require_ = createRequire(import.meta.url)

/** Every icon the web UI renders. Adding one here is the whole change. */
const ICONS = ['git-branch', 'folder', 'chat-teardrop-dots', 'arrow-line-down']

const entries = ICONS.map((name) => {
  const path = require_.resolve(`@phosphor-icons/core/regular/${name}.svg`)
  const svg = readFileSync(path, 'utf8').trim()

  if (!svg.startsWith('<svg ')) {
    throw new Error(`generate-icons: ${name}.svg is not an svg element`)
  }

  return `  '${name}':\n    '${svg.replace(/'/g, "\\'")}',`
}).join('\n')

// Read off disk rather than required. The package's exports map does not offer
// package.json, so resolving it the ordinary way throws.
const packageRoot = require_
  .resolve('@phosphor-icons/core/regular/folder.svg')
  .replace(/\/assets\/regular\/folder\.svg$/, '')
const { version } = JSON.parse(readFileSync(`${packageRoot}/package.json`, 'utf8'))

const file = `// Generated by scripts/generate-icons.mjs from @phosphor-icons/core@${version}.
// Do not edit. Run \`npm run icons\` after changing the icon list or upgrading.
//
// Phosphor Icons is MIT licensed. https://github.com/phosphor-icons/core

export const ICONS: Record<string, string> = {
${entries}
}
`

const out = new URL('../src/daemon/web/icons.generated.ts', import.meta.url)
writeFileSync(out, file)
process.stdout.write(`wrote ${ICONS.length} icons from @phosphor-icons/core@${version}\n`)
